# To use:
#
#   $ conda env create -f environment.yml  # `mamba` works too for this command
#   $ conda activate pytensor-dev
#
name: pytensor-ml
channels:
  - conda-forge
  - nvidia

dependencies:
  - python>=3.12
  - pytensor
  - pymc
  - numpy

  # GPU Stuff
  - jax
  - numpyro
  - blackjax
  - jaxlib=*=*cuda*
  - cuda-nvcc

  # For testing
  - coveralls
  - diff-cover
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-benchmark
  - pytest-mock

  # For building docs
  - sphinx
  - sphinx_rtd_theme
  - pygments
  - pydot
  - ipython

  # code style
  - ruff

  # developer tools
  - pre-commit
  - packaging
  - typing_extensions
